server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "zD07y29Ax3AyromeMRZFUHGGKSRw2orz"
  valid-duration: 10 # in seconds
  refreshable-duration: 120 # in seconds